######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 27 02:22:52 2009
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += src
